[package]
name = "egui-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
futures = "0.3.30"

[patch.crates-io]
eframe = { git = "https://github.com/emilk/egui", branch = "master" }
